### PR TITLE
fix Undefined property: stdClass::$expires

### PR DESCRIPTION
**Pull request by k1ng440**

### CODE REVIEW

**Comment by k1ng440** [comment]
Hello, Can you accept this please?

**Comment by njasm** [comment]
hi @k1ng440 yes for sure!
but did you have the time to validate that soundcloud response array have the ``expires_in`` parameter? i remember that soundcloud didn't followed exaclty the Oauth spec at the time of development of that feature.

did you had the time to test it?

**Comment by k1ng440** [comment]
Hello @njasm, yes i have and my fix works perfectly

**Comment by njasm** [comment]
ok cool thanks @k1ng440 :+1:

**Pull request merged**
